### ISSUE TITLE
this for new hfs was change?

### ISSUE THREAD

**Issue by xtruong712** [247321453/HFSTest#1]
this can unpack new hfs?

thanks you

**Comment by 247321453** [comment]
The game's hfs has already used a new password, which allows you to try with a large number of passwords. If the password is correct, the code will prompt success.

**Comment by xtruong712** [comment]
This tools for search password? How to use it? And you was succesful for unpack it 🥹🥹

**Comment by xtruong712** [comment]
I try download and see it try: xxxxxxxxx
And too much time but i dont know it is what, because i dont know how to use it for file hfs

**Comment by xtruong712** [comment]
![image](https://github.com/247321453/HFSTest/assets/72967317/7c74d80f-5d65-46d3-be86-4996d54b360b)
it show this

**Comment by xtruong712** [comment]
![image](https://github.com/247321453/HFSTest/assets/72967317/b4649b75-fe7b-4f76-bb2e-7c1db99c3fff)
too much

**Comment by 247321453** [comment]
The password entered is correct, and the Test function returns true
Test(NEW, {real passowrd}, false) == true

**Comment by xtruong712** [comment]
@247321453 so command run it is what? Drag hfs and drop to HFSTest.exe?

**Comment by 247321453** [comment]
> @247321453 so command run it is what? Drag hfs and drop to HFSTest.exe?
> 
> This tool was succesful? I was run 2-3 days

This is just a demonstration, and professional code is required for specific cracking

**Comment by xtruong712** [comment]
@247321453  so this tools need
Time for finish, now cant use?

**Comment by 247321453** [comment]
> @247321453 so this tools need Time for finish, now cant use?

The password has 14 digits and requires 52 ^ 14 attempts. This number is too large and requires a password dictionary or related algorithms to crack it.

**Comment by xtruong712** [comment]
@247321453  before Ekey(HfsV2) was try unpack and he take 2 days for get 9 password. It really too much

**Comment by xtruong712** [comment]
@247321453  have news?

**Comment by xtruong712** [comment]
@247321453  it was succesful?

**Comment by xtruong712** [comment]
This project was close?

**Comment by xtruong712** [comment]
Hi @247321453  have news update?
